language: node_js
node_js:
  - "node"
env:
  - CODECOV_TOKEN="9bc1ed47-cfbb-4ab6-a518-c3134652d599"
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
deploy:
  on:
    tags: true